title: Klise Theme
description: >-
  He's writing in Bahasa about web technology and experience as a journal  for
  documentation things that he learned, meet him <a
  href="https://github.com/piharpi" target="_blank" rel="noopener">@github</a>.
lang: en-US
timezone: Asia/Jakarta
image: assets/img/ogp.png
repo: 'https://github.com/piharpi/jekyll-klise'
mode: dark
author:
  name: Reza Asif
  bio: >-
   Big cloud to offer unlimited possibilities. 
   Single misconfig and it all goes down.
   
   This is where my story begins:
   Meet me. In my mid twenties I am Wild about solutions, 
   Curious about implementations, Eagger to secure and Motivated to break. 
   I am a security by design consultant. <a
    href="https://www.linkedin.com/in/reza-a-212a39125/" target="_blank"
    rel="noopener">@Linkedin</a>.
  username: Reza
  github: ____
  twitter: ____
  facebook: ____
  email: ____
  avatar: /assets/img/Asif.jpg
url: ''
baseurl: ''
permalink: '/:title/'
google_analytics: null
fb_appid: null
collections:
  posts:
    output: true
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
defaults:
  - scope:
      path: ''
    values:
      layout: post
      comments: false
jekyll_compose:
  post_default_front_matter:
    modified: null
    tags: []
    description: null
  draft_default_front_matter:
    modified: null
    tags: []
    description: null
number_of_posts: 5
sass:
  style: compressed
include:
  - _redirects
  - .htaccess
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
